- hosts: dev_server
  become: true
  roles:
   - role: java
   - role: user_group
   - role: tomcat8
   - role: addressbook
   - role: nginx-certbot
     vars:
       certs:
         - email: "santhu3064@gmail.com"
           domain: "addressbook-dev.devopsprofessional.co.in"

- hosts: preprod_server
  become: true
  roles:
    - role: java
    - role: user_group
    - role: tomcat8
    - role: addressbook
    - role: nginx-certbot
      vars:
        certs:
          - email: "santhu3064@gmail.com"
            domain: "addressbook-preprod.devopsprofessional.co.in"

- hosts: prod_server
  become: true
  roles:
   - role: java
   - role: user_group
   - role: tomcat8
   - role: addressbook
   - role: nginx-certbot
     vars:
       certs:
         - email: "santhu3064@gmail.com"
           domain: "addressbook-prod.devopsprofessional.co.in"
