- name: extract the nexus binary
  unarchive:
    src: "{{ tomcat_url }}"
    dest: "{{ tomcat_dir }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    extra_opts: [--strip-components=1]
    mode: 0750
    remote_src: yes
