---
- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes


- name: install nginx certbot
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - certbot
    - python3-certbot-nginx
  when:  install_certificate | bool

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
  when:  install_certificate | bool
- name: Allow all access to tcp ports
  community.general.ufw:
    rule: allow
    port: "{{ item | int }} "
    proto: tcp
  with_items: "{{ firewall_ports }}"
  when:  install_certificate | bool
