- name: Copy http conf to server
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf


- name: Copy https conf to server
  template:
    src: default-ssl.conf.j2
    dest: /etc/apache2/sites-available/default-ssl.conf

- name: Enabling https conf
  file:
    src: /etc/apache2/sites-available/default-ssl.conf
    dest: /etc/apache2/sites-enabled/default-ssl.conf
    state: link
  notify: restart apache2
