---
- name: Ensure required variables for certbot are provided
  assert:
    that:
      - certs != ""
    msg: "`Mandatory variables are missing"

- name: Install dependent packages for certbot
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"

# - name: Adding apt repo list
#   apt_repository:
#    repo: 'universe'
#    state: present
#    update_cache: yes


- name: Install certbot
  snap:
    name: certbot
    classic: yes
    state: present

- name: Create link file
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: create certificate
  command: certbot --nginx --noninteractive --agree-tos --email {{ item.email }} -d {{ item.domain }}
  with_items: "{{ certs }}"
